export interface AuditLog {
  id: string
  timestamp: string
  userId: string
  userEmail: string
  userRole: string
  action: string
  details: string
  ip: string
  userAgent: string
  targetId?: string
  targetType?: string
}

export const auditLogActions = {
  LOGIN: "login",
  LOGOUT: "logout",
  CREATE_USER: "create_user",
  UPDATE_USER: "update_user",
  DELETE_USER: "delete_user",
  ASSIGN_ROLE: "assign_role",
  REVOKE_ROLE: "revoke_role",
  ASSIGN_NUDGE: "assign_nudge",
  ADD_COINS: "add_coins",
  GRANT_PREMIUM: "grant_premium",
  REVOKE_ACCESS: "revoke_access",
  RESTORE_ACCESS: "restore_access",
  VIEW_USER_PROFILE: "view_user_profile",
  GENERATE_REPORT: "generate_report",
  SYSTEM_SETTING_CHANGE: "system_setting_change",
}

// Mock audit logs for demonstration
export const mockAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    timestamp: "2023-05-15T10:30:45Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.LOGIN,
    details: "Admin login successful",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "log-2",
    timestamp: "2023-05-15T11:15:22Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.ASSIGN_NUDGE,
    details: "Assigned 'Team Recognition' nudge",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    targetId: "user-3",
    targetType: "user",
  },
  {
    id: "log-3",
    timestamp: "2023-05-15T11:30:10Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.ADD_COINS,
    details: "Added 50 coins to user",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    targetId: "user-2",
    targetType: "user",
  },
  {
    id: "log-4",
    timestamp: "2023-05-15T13:45:33Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.LOGIN,
    details: "HR admin login successful",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "log-5",
    timestamp: "2023-05-15T14:10:05Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.GRANT_PREMIUM,
    details: "Granted premium access",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    targetId: "user-4",
    targetType: "user",
  },
  {
    id: "log-6",
    timestamp: "2023-05-15T15:20:18Z",
    userId: "admin-3",
    userEmail: "dept@example.com",
    userRole: "department_admin",
    action: auditLogActions.LOGIN,
    details: "Department admin login successful",
    ip: "192.168.1.3",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15",
  },
  {
    id: "log-7",
    timestamp: "2023-05-15T15:35:42Z",
    userId: "admin-3",
    userEmail: "dept@example.com",
    userRole: "department_admin",
    action: auditLogActions.ASSIGN_NUDGE,
    details: "Assigned 'Feedback Session' nudge",
    ip: "192.168.1.3",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15",
    targetId: "user-5",
    targetType: "user",
  },
  {
    id: "log-8",
    timestamp: "2023-05-15T16:50:27Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.REVOKE_ACCESS,
    details: "Revoked user access",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    targetId: "user-6",
    targetType: "user",
  },
  {
    id: "log-9",
    timestamp: "2023-05-15T17:05:11Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.GENERATE_REPORT,
    details: "Generated 'User Activity Summary' report",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "log-10",
    timestamp: "2023-05-15T17:30:55Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.LOGOUT,
    details: "Admin logout",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
  {
    id: "log-11",
    timestamp: "2023-05-16T09:15:30Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.LOGIN,
    details: "HR admin login successful",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "log-12",
    timestamp: "2023-05-16T09:45:18Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.ASSIGN_ROLE,
    details: "Assigned 'department_admin' role",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    targetId: "user-7",
    targetType: "user",
  },
  {
    id: "log-13",
    timestamp: "2023-05-16T10:20:05Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.ADD_COINS,
    details: "Added 100 coins to user",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    targetId: "user-8",
    targetType: "user",
  },
  {
    id: "log-14",
    timestamp: "2023-05-16T11:10:42Z",
    userId: "admin-2",
    userEmail: "hr@example.com",
    userRole: "hr_admin",
    action: auditLogActions.LOGOUT,
    details: "HR admin logout",
    ip: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
  },
  {
    id: "log-15",
    timestamp: "2023-05-16T13:30:15Z",
    userId: "admin-1",
    userEmail: "admin@example.com",
    userRole: "super_admin",
    action: auditLogActions.LOGIN,
    details: "Admin login successful",
    ip: "192.168.1.1",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  },
]
