export const mockAdminData = {
  globalMetrics: {
    totalUsers: 1250,
    activeUsers: 980,
    totalNudgesSent: 8750,
    totalNudgesCompleted: 6820,
    coinsDistributed: 42500,
    premiumNudgesUsed: 1240,
    tagsReceived: 3450,
    tagsSent: 3450,
    averageSentiment: 7.8,
    needsAttention: 85,
  },

  users: [
    {
      id: "user-1",
      name: "John Doe",
      team: "Engineering",
      role: "Team Lead",
      lastActive: "Today, 10:30 AM",
      nudgesCompleted: 45,
      nudgesMissed: 3,
      coinsEarned: 320,
      tagsReceived: 28,
      tagsSent: 35,
      status: "active",
      isPremium: true,
    },
    {
      id: "user-2",
      name: "Jane Smith",
      team: "Product",
      role: "Product Manager",
      lastActive: "Today, 9:15 AM",
      nudgesCompleted: 38,
      nudgesMissed: 5,
      coinsEarned: 280,
      tagsReceived: 22,
      tagsSent: 18,
      status: "active",
      isPremium: true,
    },
    {
      id: "user-3",
      name: "Michael Johnson",
      team: "Design",
      role: "Senior Designer",
      lastActive: "Yesterday, 4:45 PM",
      nudgesCompleted: 32,
      nudgesMissed: 8,
      coinsEarned: 210,
      tagsReceived: 15,
      tagsSent: 12,
      status: "needs_attention",
      isPremium: false,
    },
    {
      id: "user-4",
      name: "Emily Davis",
      team: "Marketing",
      role: "Marketing Lead",
      lastActive: "3 days ago",
      nudgesCompleted: 28,
      nudgesMissed: 12,
      coinsEarned: 180,
      tagsReceived: 10,
      tagsSent: 8,
      status: "needs_attention",
      isPremium: false,
    },
    {
      id: "user-5",
      name: "Robert Brown",
      team: "Engineering",
      role: "Developer",
      lastActive: "2 weeks ago",
      nudgesCompleted: 15,
      nudgesMissed: 25,
      coinsEarned: 90,
      tagsReceived: 5,
      tagsSent: 3,
      status: "suspended",
      isPremium: false,
    },
  ],

  userJourneys: [
    {
      userId: "user-1",
      userName: "John Doe",
      userRole: "Team Lead",
      userTeam: "Engineering",
      timeline: [
        {
          id: "event-1",
          date: "Today",
          time: "10:30 AM",
          type: "login",
          title: "Logged in",
          description: "User logged into the platform",
        },
        {
          id: "event-2",
          date: "Today",
          time: "10:35 AM",
          type: "nudge_completed",
          title: "Completed 'Recognize a Team Member' nudge",
          description: "Tagged Alice Smith and provided positive feedback",
        },
        {
          id: "event-3",
          date: "Today",
          time: "10:40 AM",
          type: "coins_earned",
          title: "Earned 10 coins",
          description: "Received coins for completing a nudge",
        },
        {
          id: "event-4",
          date: "Yesterday",
          time: "2:15 PM",
          type: "nudge_assigned",
          title: "Assigned 'Schedule a 1:1 Meeting' nudge",
          description: "System assigned a new leadership nudge",
        },
        {
          id: "event-5",
          date: "Yesterday",
          time: "3:30 PM",
          type: "nudge_completed",
          title: "Completed 'Schedule a 1:1 Meeting' nudge",
          description: "Scheduled meeting with Bob Johnson",
        },
        {
          id: "event-6",
          date: "Yesterday",
          time: "3:35 PM",
          type: "coins_earned",
          title: "Earned 15 coins",
          description: "Received coins for completing a nudge",
        },
        {
          id: "event-7",
          date: "2 days ago",
          time: "11:20 AM",
          type: "badge_earned",
          title: "Earned 'Team Player' badge",
          description: "Tagged team members in 5 different nudges",
        },
        {
          id: "event-8",
          date: "3 days ago",
          time: "9:45 AM",
          type: "tag_sent",
          title: "Tagged Carol Williams",
          description: "Tagged in 'Share Team Progress' nudge",
        },
        {
          id: "event-9",
          date: "3 days ago",
          time: "10:15 AM",
          type: "nudge_completed",
          title: "Completed 'Share Team Progress' nudge",
          description: "Shared project status update with the team",
        },
        {
          id: "event-10",
          date: "4 days ago",
          time: "3:50 PM",
          type: "tag_received",
          title: "Tagged by Alice Smith",
          description: "Tagged in 'Provide Constructive Feedback' nudge",
        },
        {
          id: "event-11",
          date: "5 days ago",
          time: "1:30 PM",
          type: "nudge_assigned",
          title: "Assigned 'Delegate a Task' nudge",
          description: "System assigned a new leadership nudge",
        },
        {
          id: "event-12",
          date: "5 days ago",
          time: "4:20 PM",
          type: "nudge_completed",
          title: "Completed 'Delegate a Task' nudge",
          description: "Delegated code review task to David Brown",
        },
      ],
      stats: {
        nudgesCompleted: 45,
        nudgesMissed: 3,
        coinsEarned: 320,
        tagsReceived: 28,
        tagsSent: 35,
        averageSentiment: 8.5,
        loginFrequency: 5.2,
        responseTime: 4.3,
      },
      comparisonToTeam: {
        nudgesCompleted: 25,
        coinsEarned: 18,
        engagement: 30,
        sentiment: 15,
      },
    },
  ],

  availableReports: [
    {
      id: "report-1",
      name: "User Activity Summary",
      description: "Overview of user activity, nudge completion, and engagement",
      type: "csv",
      lastGenerated: "Yesterday, 11:30 AM",
      category: "user",
    },
    {
      id: "report-2",
      name: "Nudge Effectiveness",
      description: "Analysis of nudge completion rates and user feedback",
      type: "pdf",
      lastGenerated: "3 days ago",
      category: "nudge",
    },
    {
      id: "report-3",
      name: "Team Performance",
      description: "Comparison of team engagement and leadership metrics",
      type: "excel",
      lastGenerated: "Last week",
      category: "team",
    },
    {
      id: "report-4",
      name: "Engagement Metrics",
      description: "Detailed analysis of user engagement patterns",
      type: "csv",
      category: "engagement",
    },
    {
      id: "report-5",
      name: "Premium Feature Usage",
      description: "Analysis of premium nudge usage and effectiveness",
      type: "pdf",
      lastGenerated: "2 weeks ago",
      category: "nudge",
    },
    {
      id: "report-6",
      name: "User Sentiment Analysis",
      description: "Trends in user sentiment and feedback",
      type: "excel",
      category: "user",
    },
    {
      id: "report-7",
      name: "Peer Recognition Patterns",
      description: "Analysis of peer tagging and recognition behavior",
      type: "csv",
      category: "engagement",
    },
    {
      id: "report-8",
      name: "Leadership Growth Metrics",
      description: "Tracking of leadership skill development over time",
      type: "pdf",
      category: "team",
    },
  ],
}
