// Mock user data
export const mockUserData = {
  name: "John Doe",
  email: "john@example.com",
  company: "Acme Inc.",
  role: "Team Lead",
  currentStreak: 5,
  longestStreak: 7,
  completedNudges: 23,
  completedThisWeek: 4,
  rank: 3,
  rankChange: -2, // Negative means improved rank
  companyRank: 1,
  points: 230,
  badges: [
    { id: "badge-1", name: "First Nudge" },
    { id: "badge-2", name: "3-Day Streak" },
    { id: "badge-3", name: "10 Nudges Completed" },
    { id: "badge-4", name: "Team Player" },
  ],
  recentActivity: [
    {
      type: "nudge_completed",
      title: "Completed 'Recognize a Team Member'",
      description: "You've earned 10 points",
      time: "2 hours ago",
    },
    {
      type: "badge_earned",
      title: "Earned '10 Nudges Completed' badge",
      description: "Keep up the good work!",
      time: "Yesterday",
    },
    {
      type: "streak_milestone",
      title: "Reached a 5-day streak",
      description: "You're on your way to a new badge",
      time: "Yesterday",
    },
    {
      type: "nudge_completed",
      title: "Completed 'Schedule a 1:1 Meeting'",
      description: "You've earned 10 points",
      time: "2 days ago",
    },
  ],
  teamMembers: [
    { id: "member-1", name: "Alice Smith", role: "Developer" },
    { id: "member-2", name: "Bob Johnson", role: "Designer" },
    { id: "member-3", name: "Carol Williams", role: "Product Manager" },
  ],
  upcomingNudges: [
    {
      id: "nudge-1",
      title: "Provide Constructive Feedback",
      description: "Schedule time to provide feedback to a team member",
      date: "Tomorrow",
    },
    {
      id: "nudge-2",
      title: "Celebrate Team Wins",
      description: "Recognize recent achievements in your team",
      date: "In 2 days",
    },
    {
      id: "nudge-3",
      title: "Review Team Goals",
      description: "Check progress on quarterly objectives",
      date: "Next week",
    },
  ],
}

// Mock nudges data
export const mockNudges = [
  {
    id: "nudge-1",
    title: "Recognize a Team Member",
    description:
      "Take a moment to send a thank-you note to a team member who has been performing well. Recognition boosts morale and encourages continued good work.",
    date: "Today",
    categories: ["Recognition", "Team Building"],
    completed: false,
    liked: false,
    disliked: false,
    saved: false,
    taggedMembers: [],
  },
  {
    id: "nudge-2",
    title: "Schedule a 1:1 Meeting",
    description:
      "Regular one-on-one meetings help build rapport with your team members and provide a space for open communication. Schedule a 15-30 minute check-in with someone on your team.",
    date: "Today",
    categories: ["Communication", "Mentoring"],
    completed: false,
    liked: true,
    disliked: false,
    saved: true,
    taggedMembers: ["member-1"],
  },
  {
    id: "nudge-3",
    title: "Delegate a Task",
    description:
      "Effective delegation helps develop your team members' skills and frees up your time for strategic work. Identify a task you can delegate today and provide clear instructions.",
    date: "Tomorrow",
    categories: ["Delegation", "Productivity"],
    completed: false,
    liked: false,
    disliked: false,
    saved: false,
    taggedMembers: [],
  },
  {
    id: "nudge-4",
    title: "Share Team Progress",
    description:
      "Transparency about team progress helps everyone stay aligned. Share an update on a current project with your team, highlighting achievements and next steps.",
    date: "In 2 days",
    categories: ["Communication", "Transparency"],
    completed: false,
    liked: false,
    disliked: false,
    saved: false,
    taggedMembers: [],
  },
  {
    id: "nudge-5",
    title: "Provide Constructive Feedback",
    description:
      "Timely, specific feedback helps team members grow. Schedule a short session to provide constructive feedback to someone on your team.",
    date: "In 3 days",
    categories: ["Feedback", "Mentoring"],
    completed: false,
    liked: false,
    disliked: false,
    saved: false,
    taggedMembers: [],
  },
  {
    id: "nudge-6",
    title: "Learn Something New",
    description:
      "Great leaders are continuous learners. Spend 30 minutes today reading an article, watching a video, or listening to a podcast about leadership.",
    date: "Yesterday",
    categories: ["Learning", "Self-improvement"],
    completed: true,
    liked: true,
    disliked: false,
    saved: true,
    taggedMembers: [],
  },
]

// Mock team members data
export const mockTeamMembers = [
  { id: "member-1", name: "Alice Smith", role: "Developer", email: "alice@example.com" },
  { id: "member-2", name: "Bob Johnson", role: "Designer", email: "bob@example.com" },
  { id: "member-3", name: "Carol Williams", role: "Product Manager", email: "carol@example.com" },
  { id: "member-4", name: "David Brown", role: "Developer", email: "david@example.com" },
  { id: "member-5", name: "Eva Garcia", role: "Marketing", email: "eva@example.com" },
]

// Mock leaderboard data
export const mockLeaderboardData = [
  {
    id: "user-1",
    name: "John Doe",
    company: "Acme Inc.",
    points: 230,
    rankChange: -2,
    isCurrentUser: true,
    isInMyCompany: true,
  },
  {
    id: "user-2",
    name: "Jane Smith",
    company: "Acme Inc.",
    points: 310,
    rankChange: 0,
    isCurrentUser: false,
    isInMyCompany: true,
  },
  {
    id: "user-3",
    name: "Michael Johnson",
    company: "Acme Inc.",
    points: 285,
    rankChange: -1,
    isCurrentUser: false,
    isInMyCompany: true,
  },
  {
    id: "user-4",
    name: "Sarah Williams",
    company: "TechCorp",
    points: 340,
    rankChange: 0,
    isCurrentUser: false,
    isInMyCompany: false,
  },
  {
    id: "user-5",
    name: "Robert Brown",
    company: "TechCorp",
    points: 220,
    rankChange: 2,
    isCurrentUser: false,
    isInMyCompany: false,
  },
  {
    id: "user-6",
    name: "Emily Davis",
    company: "Globex",
    points: 190,
    rankChange: -3,
    isCurrentUser: false,
    isInMyCompany: false,
  },
  {
    id: "user-7",
    name: "David Miller",
    company: "Initech",
    points: 175,
    rankChange: 1,
    isCurrentUser: false,
    isInMyCompany: false,
  },
  {
    id: "user-8",
    name: "Lisa Wilson",
    company: "Acme Inc.",
    points: 160,
    rankChange: 0,
    isCurrentUser: false,
    isInMyCompany: true,
  },
  {
    id: "user-9",
    name: "James Taylor",
    company: "Globex",
    points: 150,
    rankChange: -1,
    isCurrentUser: false,
    isInMyCompany: false,
  },
  {
    id: "user-10",
    name: "Patricia Moore",
    company: "TechCorp",
    points: 145,
    rankChange: 2,
    isCurrentUser: false,
    isInMyCompany: false,
  },
]

// Mock chat data
export const mockChatData = [
  {
    id: "chat-1",
    type: "direct",
    name: "Alice Smith",
    lastMessage: "I'll complete that nudge by tomorrow",
    lastMessageTime: "10:30 AM",
    unreadCount: 2,
    messages: [
      {
        id: "msg-1",
        sender: "other",
        text: "Hi there! Did you see today's leadership nudge?",
        time: "10:15 AM",
        status: "read",
      },
      {
        id: "msg-2",
        sender: "current-user",
        text: "Yes, it's about recognizing team members. I think it's a good reminder.",
        time: "10:20 AM",
        status: "read",
      },
      {
        id: "msg-3",
        sender: "other",
        text: "Definitely! I've been trying to be more intentional about that. By the way, I wanted to let you know I'll complete that task we discussed by tomorrow.",
        time: "10:25 AM",
        status: "read",
      },
      {
        id: "msg-4",
        sender: "other",
        text: "I'll complete that nudge by tomorrow",
        time: "10:30 AM",
        status: "delivered",
      },
    ],
    members: ["user-1", "member-1"],
  },
  {
    id: "chat-2",
    type: "direct",
    name: "Bob Johnson",
    lastMessage: "Thanks for the feedback!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    messages: [
      {
        id: "msg-1",
        sender: "current-user",
        text: "Hi Bob, I wanted to give you some feedback on your recent design work.",
        time: "Yesterday, 2:15 PM",
        status: "read",
      },
      {
        id: "msg-2",
        sender: "other",
        text: "Sure, I'd appreciate that!",
        time: "Yesterday, 2:20 PM",
        status: "read",
      },
      {
        id: "msg-3",
        sender: "current-user",
        text: "The new dashboard layout is really intuitive and clean. Great job on simplifying the navigation.",
        time: "Yesterday, 2:25 PM",
        status: "read",
      },
      {
        id: "msg-4",
        sender: "other",
        text: "Thanks for the feedback!",
        time: "Yesterday, 2:30 PM",
        status: "read",
      },
    ],
    members: ["user-1", "member-2"],
  },
  {
    id: "chat-3",
    type: "group",
    name: "Product Team",
    lastMessage: "Let's discuss this in our meeting tomorrow",
    lastMessageTime: "Yesterday",
    unreadCount: 1,
    messages: [
      {
        id: "msg-1",
        sender: "member-3",
        text: "Hi team, I've shared the Q3 goals in our shared workspace.",
        time: "Yesterday, 11:15 AM",
        status: "read",
      },
      {
        id: "msg-2",
        sender: "member-1",
        text: "Thanks Carol! I'll review them today.",
        time: "Yesterday, 11:20 AM",
        status: "read",
      },
      {
        id: "msg-3",
        sender: "member-2",
        text: "I have some questions about the UX improvements goal. Can we discuss that in more detail?",
        time: "Yesterday, 11:30 AM",
        status: "read",
      },
      {
        id: "msg-4",
        sender: "member-3",
        text: "Let's discuss this in our meeting tomorrow",
        time: "Yesterday, 11:35 AM",
        status: "read",
      },
    ],
    members: ["user-1", "member-1", "member-2", "member-3"],
  },
  {
    id: "chat-4",
    type: "group",
    name: "Leadership Circle",
    lastMessage: "I found this article on effective delegation",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
    messages: [
      {
        id: "msg-1",
        sender: "other",
        text: "Has anyone tried the new delegation nudge?",
        time: "2 days ago, 3:15 PM",
        status: "read",
      },
      {
        id: "msg-2",
        sender: "current-user",
        text: "Yes, I've been working on delegating more effectively this quarter.",
        time: "2 days ago, 3:20 PM",
        status: "read",
      },
      {
        id: "msg-3",
        sender: "other",
        text: "I found this article on effective delegation: https://example.com/delegation-tips",
        time: "2 days ago, 3:30 PM",
        status: "read",
      },
    ],
    members: ["user-1", "user-2", "user-3", "user-4"],
  },
]
